name: blaz
description: FrameWork for dart backend.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.8.0
  colorize: any
  mime: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
